server:
  port: 9999
spring:
  application:
    name: creativity-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.24.233:3306/creativity_web
    username: cradmin
    password: CRadmin.888
  cloud: #nacos地址
    nacos:
      server-addr: nacos-server:8848
      config:
        file-extension: yaml
    profiles:
      active: dev

#拉取的配置文件DataID : creativity-service-dev.yaml


