server:
  port: 9999
spring:
  application:
    name: creativity-service
#  cloud: #nacos地址
#    nacos:
#      server-addr: nacos-server:8848
#      config:
#        file-extension: yaml
#    profiles:
#      active: dev




#拉取的配置文件DataID : creativity-service-dev.yaml


